name: rag-workflow-Financial crisis
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python Financial_crisis.py
          
       
          echo "oky raed -------"
          echo "oky raed 2 -------"
         
          echo "## Data correlation" >> report.md
          cml-publish SP_500_data_commodities_data.png --md >> report.md
          
          echo "## Financial_crisis" >> report.md
          cml-publish Financial_crisis.png --md >> report.md

          echo "## state 0: " >> report.md
          cml-publish stat_0_.png --md >> report.md

          echo "## state 1: " >> report.md
          cml-publish stat_1_.png --md >> report.md

          echo "## state 2: " >> report.md
          cml-publish stat_2_.png --md >> report.md

          echo "## state 3: " >> report.md
          cml-publish stat_3_.png --md >> report.md

          echo "## state 4: " >> report.md
          cml-publish stat_4_.png --md >> report.md

          echo "## state 5: " >> report.md
          cml-publish stat_5_.png --md >> report.md

          echo "## state 6: " >> report.md
          cml-publish stat_6_.png --md >> report.md

          echo "## state 7: " >> report.md
          cml-publish stat_7_.png --md >> report.md
        
          
          cml-send-comment report.md
      
